# Generated by Django 5.1.1 on 2024-12-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('clss_no', models.IntegerField()),
                ('Mark', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
